In [ ]:
#q1

In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list, whereas array_list is a numpy array.

To print the data types of both variables, you can use the type() function:

In [2]:
# Define the list
import numpy as np
list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
#q2

In [3]:
import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
#q3

In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list after applying the dtype parameter as int.

When we set dtype=int while creating the numpy array array_list, all the elements of the original list_ are converted to integers. Therefore, the data type of the elements in array_list will be int instead of str (which was the original data type of the elements in list_).

In [4]:
import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert list to numpy array with dtype as int
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
#q4

In [5]:
import numpy as np

# Define the nested list
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert list to numpy array
num_array = np.array(object=num_list)

# Find the shape of the array
print("Shape of num_array:", num_array.shape)

# Find the size of the array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
#q5

In [6]:
import numpy as np

# Create a 3x3 numpy array containing only zeros
zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#q6

In [7]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.identity(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
